### ISSUE TITLE
cursor displayed twice

### ISSUE THREAD

**Issue by sebastienserre** [qstudio/advanced-custom-fields-number-slider#2]
Hello

my slider is displayed in 2 line:
https://dl.dropboxusercontent.com/1/view/7vm7jt2przlcuh6/Apps/Shutter/capture_059.jpg

Any idea why ?

**Comment by qstudio** [comment]
Sorry, we totally did not see this!.. It might be a case of having the same field included twice or a JS bug, check the console for errors

**Comment by qstudio** [comment]
closing this up to keep things tidy
