### ISSUE TITLE
Bug in 

### ISSUE THREAD

**Issue by bamboorocket** [qstudio/advanced-custom-fields-number-slider#5]
at line 262 missing // to comment out line 

\w__log( $field.' - '.$value );

should be 

//      \w__log( $field.' - '.$value );

**Comment by qstudio** [comment]
Yep! good spot, will push a release soon as possible.

**Comment by qstudio** [comment]
Actually, @bamboorocket - can you link us to the file where you see this error, as a search does not show it?

**Comment by qstudio** [comment]
Ok, spotted and nailed, 0.5.9 released here and on WP.org
